AWSTemplateFormatVersion: '2010-09-09'
Description: "flows gmail"
Resources:
  newmailFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: newmail
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
  fetchmailFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: fetchmail
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
  fetchmailsimplifiedFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: fetchmailsimplified
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
  fetchmailrawFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: fetchmailraw
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
  fetchmailrawLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: fetchmailrawFunction
      RetentionInDays: 7
  fetchmailsimplifiedLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: fetchmailsimplifiedFunction
      RetentionInDays: 7
  fetchmailLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: fetchmailFunction
      RetentionInDays: 7
  newmailLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: newmailFunction
      RetentionInDays: 7
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
  InvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - 321232316075
            - 184705290838
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - lambda:InvokeFunction
              Resource:
              - Fn::GetAtt: [ newmailFunction , Arn ]
              - Fn::GetAtt: [ fetchmailFunction , Arn ]
              - Fn::GetAtt: [ fetchmailsimplifiedFunction , Arn ]
              - Fn::GetAtt: [ fetchmailrawFunction , Arn ]
Outputs:
  newmailFunction:
    Description: 'newmail'
    Value:
      Fn::GetAtt: [ newmailFunction , Arn ]
  newmailRole:
    Description: 'newmail'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  fetchmailFunction:
    Description: 'fetchmail'
    Value:
      Fn::GetAtt: [ fetchmailFunction , Arn ]
  fetchmailRole:
    Description: 'fetchmail'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  fetchmailsimplifiedFunction:
    Description: 'fetchmailsimplified'
    Value:
      Fn::GetAtt: [ fetchmailsimplifiedFunction , Arn ]
  fetchmailsimplifiedRole:
    Description: 'fetchmailsimplified'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  fetchmailrawFunction:
    Description: 'fetchmailraw'
    Value:
      Fn::GetAtt: [ fetchmailrawFunction , Arn ]
  fetchmailrawRole:
    Description: 'fetchmailraw'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
