AWSTemplateFormatVersion: '2010-09-09'
Description: "meshify gmail"
Resources:
  MESHIFYgmailnewmailFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: MESHIFY_gmail_newmail
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
  MESHIFYgmailfetchmailFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: MESHIFY_gmail_fetchmail
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
  MESHIFYgmailfetchmailsimplifiedFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: MESHIFY_gmail_fetchmailsimplified
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
  MESHIFYgmailfetchmailrawFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: MESHIFY_gmail_fetchmailraw
      Handler: main.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: python3.6
      Timeout: 300
  MESHIFYgmailfetchmailrawLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: MESHIFYgmailfetchmailrawFunction
      RetentionInDays: 7
  MESHIFYgmailfetchmailsimplifiedLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: MESHIFYgmailfetchmailsimplifiedFunction
      RetentionInDays: 7
  MESHIFYgmailfetchmailLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: MESHIFYgmailfetchmailFunction
      RetentionInDays: 7
  MESHIFYgmailnewmailLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/aws/lambda/"
            - Ref: MESHIFYgmailnewmailFunction
      RetentionInDays: 7
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
  InvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - 321232316075
            - 184705290838
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - lambda:InvokeFunction
              Resource:
              - Fn::GetAtt: [ MESHIFYgmailnewmailFunction , Arn ]
              - Fn::GetAtt: [ MESHIFYgmailfetchmailFunction , Arn ]
              - Fn::GetAtt: [ MESHIFYgmailfetchmailsimplifiedFunction , Arn ]
              - Fn::GetAtt: [ MESHIFYgmailfetchmailrawFunction , Arn ]
Outputs:
  MESHIFYgmailnewmailFunction:
    Description: '/MESHIFY/MESHIFY/gmail/newmail/lambda'
    Value:
      Fn::GetAtt: [ MESHIFYgmailnewmailFunction , Arn ]
  MESHIFYgmailnewmailRole:
    Description: '/MESHIFY/MESHIFY/gmail/newmail/role'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  MESHIFYgmailfetchmailFunction:
    Description: '/MESHIFY/MESHIFY/gmail/fetchmail/lambda'
    Value:
      Fn::GetAtt: [ MESHIFYgmailfetchmailFunction , Arn ]
  MESHIFYgmailfetchmailRole:
    Description: '/MESHIFY/MESHIFY/gmail/fetchmail/role'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  MESHIFYgmailfetchmailsimplifiedFunction:
    Description: '/MESHIFY/MESHIFY/gmail/fetchmailsimplified/lambda'
    Value:
      Fn::GetAtt: [ MESHIFYgmailfetchmailsimplifiedFunction , Arn ]
  MESHIFYgmailfetchmailsimplifiedRole:
    Description: '/MESHIFY/MESHIFY/gmail/fetchmailsimplified/role'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
  MESHIFYgmailfetchmailrawFunction:
    Description: '/MESHIFY/MESHIFY/gmail/fetchmailraw/lambda'
    Value:
      Fn::GetAtt: [ MESHIFYgmailfetchmailrawFunction , Arn ]
  MESHIFYgmailfetchmailrawRole:
    Description: '/MESHIFY/MESHIFY/gmail/fetchmailraw/role'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
